### ISSUE TITLE
tested latest version in 1.11.2 elgg and got a fatal error on activation

### ISSUE THREAD

**Issue by propertunist** [ColdTrick/menu_builder#24] opened 2015-06-07 19:57 UTC
the plugin is activated, however, there are no visual effects in the gui of the site to show that menu_builder is active.

```
Fatal Error.

Duplicate entry '52-active_plugin-1' for key 'guid_one'

QUERY: INSERT INTO entity_relationships
(guid_one, relationship, guid_two, time_created)
VALUES (52, 'active_plugin', 1, 1433706691)

DatabaseException Object
(
[message:protected] => Duplicate entry '52-active_plugin-1' for key 'guid_one'

QUERY: INSERT INTO entity_relationships
(guid_one, relationship, guid_two, time_created)
VALUES (52, 'active_plugin', 1, 1433706691)
[string:Exception:private] => exception 'DatabaseException' with message 'Duplicate entry '52-active_plugin-1' for key 'guid_one'

QUERY: INSERT INTO entity_relationships
(guid_one, relationship, guid_two, time_created)
VALUES (52, 'active_plugin', 1, 1433706691)' in /var/www/html/dev.ureka.1.11.2/engine/classes/Elgg/Database.php:406
Stack trace:
#0 /var/www/html/dev.ureka.1.11.2/engine/classes/Elgg/Database.php(215): Elgg\Database->executeQuery('INSERT INTO ent...', Resource id #73)
#1 /var/www/html/dev.ureka.1.11.2/engine/classes/Elgg/Database/RelationshipsTable.php(115): Elgg\Database->insertData('INSERT INTO ent...')
#2 /var/www/html/dev.ureka.1.11.2/engine/lib/relationships.php(74): Elgg\Database\RelationshipsTable->add(52, 'active_plugin', 1)
#3 /var/www/html/dev.ureka.1.11.2/engine/classes/ElggPlugin.php(972): add_entity_relationship(52, 'active_plugin', 1)
#4 /var/www/html/dev.ureka.1.11.2/engine/classes/ElggPlugin.php(654): ElggPlugin->setStatus(true, NULL)
#5 /var/www/html/dev.ureka.1.11.2/actions/admin/plugins/activate.php(29): ElggPlugin->activate()
#6 /var/www/html/dev.ureka.1.11.2/engine/classes/Elgg/ActionsService.php(88): include('/var/www/html/d...')
#7 /var/www/html/dev.ureka.1.11.2/engine/classes/Elgg/ActionsService.php(70): Elgg\ActionsService::includeFile('/var/www/html/d...')
#8 /var/www/html/dev.ureka.1.11.2/engine/lib/actions.php(20): Elgg\ActionsService->execute('admin/plugins/a...')
#9 [internal function]: _elgg_action_handler(Array, 'action')
#10 /var/www/html/dev.ureka.1.11.2/engine/classes/Elgg/Router.php(80): call_user_func('_elgg_action_ha...', Array, 'action')
#11 /var/www/html/dev.ureka.1.11.2/index.php(60): Elgg\Router->route(Object(Elgg\Http\Request))
#12 {main}
[code:protected] => 0
[file:protected] => /var/www/html/dev.ureka.1.11.2/engine/classes/Elgg/Database.php
[line:protected] => 406
[trace:Exception:private] => Array
(
[0] => Array
(
[file] => /var/www/html/dev.ureka.1.11.2/engine/classes/Elgg/Database.php
[line] => 215
[function] => executeQuery
[class] => Elgg\Database
[type] => ->
[args] => Array
(
[0] => INSERT INTO entity_relationships
(guid_one, relationship, guid_two, time_created)
VALUES (52, 'active_plugin', 1, 1433706691)
[1] => Resource id #73
)

)

[1] => Array
(
[file] => /var/www/html/dev.ureka.1.11.2/engine/classes/Elgg/Database/RelationshipsTable.php
[line] => 115
[function] => insertData
[class] => Elgg\Database
[type] => ->
[args] => Array
(
[0] => INSERT INTO entity_relationships
(guid_one, relationship, guid_two, time_created)
VALUES (52, 'active_plugin', 1, 1433706691)
)

)

[2] => Array
(
[file] => /var/www/html/dev.ureka.1.11.2/engine/lib/relationships.php
[line] => 74
[function] => add
[class] => Elgg\Database\RelationshipsTable
[type] => ->
[args] => Array
(
[0] => 52
[1] => active_plugin
[2] => 1
)

)

[3] => Array
(
[file] => /var/www/html/dev.ureka.1.11.2/engine/classes/ElggPlugin.php
[line] => 972
[function] => add_entity_relationship
[args] => Array
(
[0] => 52
[1] => active_plugin
[2] => 1
)

)

[4] => Array
(
[file] => /var/www/html/dev.ureka.1.11.2/engine/classes/ElggPlugin.php
[line] => 654
[function] => setStatus
[class] => ElggPlugin
[type] => ->
[args] => Array
(
[0] => 1
[1] =>
)

)

[5] => Array
(
[file] => /var/www/html/dev.ureka.1.11.2/actions/admin/plugins/activate.php
[line] => 29
[function] => activate
[class] => ElggPlugin
[type] => ->
[args] => Array
(
)

)

[6] => Array
(
[file] => /var/www/html/dev.ureka.1.11.2/engine/classes/Elgg/ActionsService.php
[line] => 88
[args] => Array
(
[0] => /var/www/html/dev.ureka.1.11.2/actions/admin/plugins/activate.php
)

[function] => include
)

[7] => Array
(
[file] => /var/www/html/dev.ureka.1.11.2/engine/classes/Elgg/ActionsService.php
[line] => 70
[function] => includeFile
[class] => Elgg\ActionsService
[type] => ::
[args] => Array
(
[0] => /var/www/html/dev.ureka.1.11.2/actions/admin/plugins/activate.php
)

)

[8] => Array
(
[file] => /var/www/html/dev.ureka.1.11.2/engine/lib/actions.php
[line] => 20
[function] => execute
[class] => Elgg\ActionsService
[type] => ->
[args] => Array
(
[0] => admin/plugins/activate
)

)

[9] => Array
(
[function] => _elgg_action_handler
[args] => Array
(
[0] => Array
(
[0] => admin
[1] => plugins
[2] => activate
)

[1] => action
)

)

[10] => Array
(
[file] => /var/www/html/dev.ureka.1.11.2/engine/classes/Elgg/Router.php
[line] => 80
[function] => call_user_func
[args] => Array
(
[0] => _elgg_action_handler
[1] => Array
(
[0] => admin
[1] => plugins
[2] => activate
)

[2] => action
)

)

[11] => Array
(
[file] => /var/www/html/dev.ureka.1.11.2/index.php
[line] => 60
[function] => route
[class] => Elgg\Router
[type] => ->
[args] => Array
(
[0] => Elgg\Http\Request Object
(
[attributes] => Symfony\Component\HttpFoundation\ParameterBag Object
(
[parameters:protected] => Array
(
)

)

[request] => Symfony\Component\HttpFoundation\ParameterBag Object
(
[parameters:protected] => Array
(
)

)

[query] => Symfony\Component\HttpFoundation\ParameterBag Object
(
[parameters:protected] => Array
(
[__elgg_uri] => /action/admin/plugins/activate
[plugin_guids] => Array
(
[0] => 52
)

[__elgg_ts] => 1433706683
[__elgg_token] => AoE57oh1uy626-8rvRg5_A
)

)

[server] => Symfony\Component\HttpFoundation\ServerBag Object
(
[parameters:protected] => Array
(
[USER] => nginx
[HOME] => /var/lib/nginx
[FCGI_ROLE] => RESPONDER
[SCRIPT_FILENAME] => /var/www/html/dev.ureka.1.11.2/index.php
[QUERY_STRING] => __elgg_uri=/action/admin/plugins/activate&plugin_guids%5B0%5D=52&__elgg_ts=1433706683&__elgg_token=AoE57oh1uy626-8rvRg5_A
[REQUEST_METHOD] => GET
[CONTENT_TYPE] =>
[CONTENT_LENGTH] =>
[SCRIPT_NAME] => /index.php
[REQUEST_URI] => /action/admin/plugins/activate?plugin_guids%5B0%5D=52&__elgg_ts=1433706683&__elgg_token=AoE57oh1uy626-8rvRg5_A
[DOCUMENT_URI] => /index.php
[DOCUMENT_ROOT] => /var/www/html/dev.ureka.1.11.2
[SERVER_PROTOCOL] => HTTP/1.1
[GATEWAY_INTERFACE] => CGI/1.1
[SERVER_SOFTWARE] => nginx/1.9.1
[REMOTE_ADDR] => 127.0.0.1
[REMOTE_PORT] => 45675
[SERVER_ADDR] => 127.0.0.1
[SERVER_PORT] => 80
[SERVER_NAME] => dev.new.ureka.org
[REDIRECT_STATUS] => 200
[HTTP_HOST] => dev.new.ureka.org
[HTTP_USER_AGENT] => Mozilla/5.0 (X11; Fedora; Linux x86_64; rv:38.0) Gecko/20100101 Firefox/38.0
[HTTP_ACCEPT] => text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
[HTTP_ACCEPT_LANGUAGE] => en-GB,en;q=0.5
[HTTP_ACCEPT_ENCODING] => gzip, deflate
[HTTP_REFERER] => http://dev.new.ureka.org/admin/plugins
[HTTP_COOKIE] => Elgg_install=jeb2iifklljdqttnrhm990smm3; Elgg=gb8ikaemoqap01nconfhjjeqd6; _pk_id.1.5a03=216c0111b630adba.1433698796.2.1433706686.1433706667.; _pk_ses.1.5a03=*
[HTTP_CONNECTION] => keep-alive
[PHP_SELF] => /index.php
[REQUEST_TIME_FLOAT] => 1433706690.1296
[REQUEST_TIME] => 1433706690
)

)

[files] => Symfony\Component\HttpFoundation\FileBag Object
(
[parameters:protected] => Array
(
)

)

[cookies] => Symfony\Component\HttpFoundation\ParameterBag Object
(
[parameters:protected] => Array
(
[Elgg_install] => jeb2iifklljdqttnrhm990smm3
[Elgg] => gb8ikaemoqap01nconfhjjeqd6
[_pk_id_1_5a03] => 216c0111b630adba.1433698796.2.1433706686.1433706667.
[_pk_ses_1_5a03] => *
)

)

[headers] => Symfony\Component\HttpFoundation\HeaderBag Object
(
[headers:protected] => Array
(
[content-type] => Array
(
[0] =>
)

[content-length] => Array
(
[0] =>
)

[host] => Array
(
[0] => dev.new.ureka.org
)

[user-agent] => Array
(
[0] => Mozilla/5.0 (X11; Fedora; Linux x86_64; rv:38.0) Gecko/20100101 Firefox/38.0
)

[accept] => Array
(
[0] => text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
)

[accept-language] => Array
(
[0] => en-GB,en;q=0.5
)

[accept-encoding] => Array
(
[0] => gzip, deflate
)

[referer] => Array
(
[0] => http://dev.new.ureka.org/admin/plugins
)

[cookie] => Array
(
[0] => Elgg_install=jeb2iifklljdqttnrhm990smm3; Elgg=gb8ikaemoqap01nconfhjjeqd6; _pk_id.1.5a03=216c0111b630adba.1433698796.2.1433706686.1433706667.; _pk_ses.1.5a03=*
)

[connection] => Array
(
[0] => keep-alive
)

)

[cacheControl:protected] => Array
(
)

)

[content:protected] =>
[languages:protected] =>
[charsets:protected] =>
[encodings:protected] =>
[acceptableContentTypes:protected] =>
[pathInfo:protected] =>
[requestUri:protected] => /action/admin/plugins/activate?plugin_guids%5B0%5D=52&__elgg_ts=1433706683&__elgg_token=AoE57oh1uy626-8rvRg5_A
[baseUrl:protected] =>
[basePath:protected] =>
[method:protected] =>
[format:protected] =>
[session:protected] =>
[locale:protected] =>
[defaultLocale:protected] => en
)

)

)

)

[previous:Exception:private] =>
)
```

**Comment by jdalsem** [comment] 2015-06-08 11:48
Is this a clean 1.11.2 install? Because the error indicates some problem with core (try to activate a plugin), not something related to this plugin (only while doing it).

**Comment by propertunist** [comment] 2015-06-08 13:06
yes, i have not edited core elgg at all. i just deactivated menu_builder and activated it again; this time i saw no fatal error, but instead there was a red warning saying 'could not activated menu builder'.. however, the plugin is shown as being active in the plugin list. the site's menu bar has not been effected at all.

**Comment by jdalsem** [comment] 2015-06-09 08:23
> Is this a clean 1.11.2 install

with a clean install i mean a fresh install, or an upgraded site. Could there be other (non core/bundled) plugins that interfere with the plugin activation?

**Comment by propertunist** [comment] 2015-06-09 10:58
this was a fresh install, yes.
i do have some other, non-core plugins active in there - though i am not aware of any that would be interfering with menu_builder. i have been using menu_builder with 1.8 elgg and all these same plugins already without any problems. i could disable all the other plugins to test menu_builder but i'd need to come back to that as i am partway through making other changes presently.

**Comment by beck24** [comment] 2015-09-25 19:12
I just activated this on a fresh 1.12.4 install, no issues

**Comment by beck24** [comment] 2015-09-25 19:27
I have it working on 1.12.4 but had to change fancybox references to colorbox and input/url to input/text

**Comment by jdalsem** [comment] 2015-12-11 11:11
Closing this as the reported issue can not be reproduced.

**Closed by jdalsem** 2015-12-11 11:11 UTC
